### ISSUE TITLE
Ошибка при добавлении зависимости

### ISSUE THREAD

**Issue by bgrebennikov** [Skeptick/vk-api-kotlin-client#2]
при добавлении строчки  maven { url "https://dl.bintray.com/skeptick/maven/" }
Появляется ошибка 403 Forbidden

**Comment by Skeptick** [comment]
Приветствую. Увы, репозиторий bintray был закрыт, соответственно, все опубликованные на нём библиотеки более недоступны.
Надо отметить, что я давно не занимался обновлением библиотеки, а зная, как VK любят ломать обратную совместимость, некоторые методы наверняка не будут работать корректно.
Я в данный момент в развитии библиотеки не заинтересован и рекомендовал бы поискать другую реализацию клиента для VK API, но если вас это не останавливает, или вы готовы поспособствовать pull request-ами в фиксе возможных проблем, то я могу опубликовать библиотеку в другом репозитории.
